import type { Project } from "./types"

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Inteligencia Artificial en Educación Superior",
    description: "Revisión sistemática sobre el impacto de la IA en metodologías de enseñanza universitaria",
    status: "in-progress",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-20"),
    ownerId: "1",
    ownerName: "Juan Pérez",
    collaborators: ["María García", "Carlos López"],
    protocol: {
      researchQuestions: [
        "¿Cómo impacta la IA en el aprendizaje estudiantil?",
        "¿Qué metodologías de IA son más efectivas?",
      ],
      picoFramework: {
        population: "Estudiantes universitarios",
        intervention: "Herramientas de IA educativa",
        comparison: "Métodos tradicionales",
        outcome: "Rendimiento académico",
      },
      inclusionCriteria: ["Publicaciones 2018-2024", "Estudios empíricos", "Idioma inglés o español"],
      exclusionCriteria: ["Estudios sin datos cuantitativos", "Educación primaria/secundaria"],
    },
    references: {
      total: 245,
      screened: 180,
      included: 45,
      excluded: 135,
    },
    prismaCompliance: 78,
  },
  {
    id: "2",
    title: "Ciberseguridad en IoT Militar",
    description: "Análisis de vulnerabilidades y soluciones en dispositivos IoT para aplicaciones militares",
    status: "screening",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-18"),
    ownerId: "1",
    ownerName: "Juan Pérez",
    collaborators: ["Ana Martínez"],
    protocol: {
      researchQuestions: ["¿Cuáles son las principales vulnerabilidades en IoT militar?"],
      inclusionCriteria: ["Publicaciones 2020-2024", "Revisión por pares"],
      exclusionCriteria: ["IoT comercial", "Estudios teóricos sin validación"],
    },
    references: {
      total: 156,
      screened: 89,
      included: 23,
      excluded: 66,
    },
    prismaCompliance: 65,
  },
  {
    id: "3",
    title: "Machine Learning en Diagnóstico Médico",
    description: "Efectividad de algoritmos ML en detección temprana de enfermedades cardiovasculares",
    status: "draft",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-15"),
    ownerId: "1",
    ownerName: "Juan Pérez",
    collaborators: [],
    references: {
      total: 0,
      screened: 0,
      included: 0,
      excluded: 0,
    },
  },
]
