import type { Reference } from "./types"

export const mockReferences: Reference[] = [
  {
    id: "1",
    projectId: "1",
    title: "Artificial Intelligence in Higher Education: A Systematic Review",
    authors: ["Smith, J.", "Johnson, M.", "Williams, K."],
    year: 2023,
    abstract:
      "This systematic review examines the impact of AI technologies on higher education learning outcomes. We analyzed 45 studies published between 2018-2023, focusing on AI-powered tutoring systems, adaptive learning platforms, and automated assessment tools. Results indicate significant improvements in student engagement and performance.",
    source: "IEEE Xplore",
    doi: "10.1109/example.2023.001",
    status: "pending",
    screeningScore: 0.92,
  },
  {
    id: "2",
    projectId: "1",
    title: "Machine Learning Applications in University Teaching Methods",
    authors: ["García, A.", "López, R."],
    year: 2022,
    abstract:
      "We present a comprehensive analysis of machine learning applications in university teaching. Our study covers personalized learning paths, intelligent content recommendation, and predictive analytics for student success. Data from 12 universities shows promising results in retention rates.",
    source: "ACM Digital Library",
    doi: "10.1145/example.2022.002",
    status: "pending",
    screeningScore: 0.88,
  },
  {
    id: "3",
    projectId: "1",
    title: "Traditional Teaching Methods: A Historical Perspective",
    authors: ["Brown, T."],
    year: 2019,
    abstract:
      "This paper explores traditional teaching methodologies used in universities over the past century. We examine lecture-based instruction, textbook learning, and conventional assessment methods without technological intervention.",
    source: "SpringerLink",
    status: "pending",
    screeningScore: 0.34,
  },
  {
    id: "4",
    projectId: "1",
    title: "Deep Learning for Educational Data Mining",
    authors: ["Chen, L.", "Wang, X.", "Zhang, Y."],
    year: 2024,
    abstract:
      "This research investigates deep learning techniques for mining educational data in higher education contexts. We propose novel neural network architectures for predicting student performance, identifying at-risk students, and optimizing curriculum design based on learning analytics.",
    source: "Scopus",
    doi: "10.1016/example.2024.003",
    status: "included",
    screeningScore: 0.95,
    reviewedBy: "María García",
    reviewedAt: new Date("2024-03-15"),
  },
  {
    id: "5",
    projectId: "1",
    title: "AI in Primary School Education",
    authors: ["Davis, P.", "Miller, S."],
    year: 2023,
    abstract:
      "An exploration of artificial intelligence applications in primary school settings. We focus on elementary education (grades K-5) and examine how AI-powered educational games and interactive learning tools affect young children's cognitive development.",
    source: "Google Scholar",
    status: "excluded",
    screeningScore: 0.41,
    reviewedBy: "Carlos López",
    reviewedAt: new Date("2024-03-10"),
    notes: "Excluido: Enfocado en educación primaria, no universitaria",
  },
  {
    id: "6",
    projectId: "1",
    title: "Chatbots and Virtual Assistants in University Learning Environments",
    authors: ["Anderson, K.", "Taylor, M."],
    year: 2023,
    abstract:
      "This study evaluates the effectiveness of AI-powered chatbots and virtual assistants in supporting university students. We conducted a randomized controlled trial with 500 students, measuring engagement, satisfaction, and academic outcomes across STEM courses.",
    source: "Web of Science",
    doi: "10.1002/example.2023.004",
    status: "pending",
    screeningScore: 0.89,
  },
  {
    id: "7",
    projectId: "1",
    title: "Theoretical Frameworks for AI in Education",
    authors: ["Martinez, R."],
    year: 2021,
    abstract:
      "A theoretical exploration of pedagogical frameworks for integrating artificial intelligence in educational contexts. This conceptual paper proposes new theoretical models without empirical validation or quantitative data.",
    source: "ScienceDirect",
    status: "pending",
    screeningScore: 0.52,
  },
  {
    id: "8",
    projectId: "1",
    title: "Automated Essay Scoring Systems in Higher Education",
    authors: ["Wilson, J.", "Thompson, A.", "Harris, B."],
    year: 2022,
    abstract:
      "We investigate the accuracy and reliability of AI-based automated essay scoring systems in university writing courses. Our analysis includes comparison with human graders, bias detection, and student perception surveys across 8 institutions.",
    source: "IEEE Xplore",
    doi: "10.1109/example.2022.005",
    status: "included",
    screeningScore: 0.91,
    reviewedBy: "María García",
    reviewedAt: new Date("2024-03-18"),
  },
]
